WEB_PROGRAMLAMA_PROJESI_2024/Controllers/AIController.cs
using Microsoft.AspNetCore.Mvc;
using RestSharp;
using System.Text;

namespace WEB_PROGRAMLAMA_PROJESI_2024.Controllers
{
    public class AIController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ApplyHairStyle(IFormFile imageFile, string hairStyle)
        {
            if (imageFile == null || imageFile.Length == 0)
            {
                return BadRequest("Lütfen geçerli bir görsel yükleyin.");
            }

            // Görseli geçici bir dosyaya kaydet
            var tempFilePath = Path.GetTempFileName();
            try
            {
                using (var stream = new FileStream(tempFilePath, FileMode.Create))
                {
                    await imageFile.CopyToAsync(stream);
                }

                // API İsteği
                var options = new RestClientOptions("https://www.ailabapi.com")
                {
                    MaxTimeout = -1
                };
                var client = new RestClient(options);
                var request = new RestRequest("/api/portrait/effects/hairstyle-editor", Method.Post);
                request.AddHeader("ailabapi-api-key", "kbMFSNOLT94DOG7F05knPEmxImXhNatY2RLtTJeosMUHwzUPcjvQj1GSf3HAdfhn");
                request.AlwaysMultipartFormData = true;
                request.AddFile("image_target", tempFilePath);
                request.AddParameter("hair_type", hairStyle);


                //request.AddParameter("hair_type", "201");
                request.AddParameter("task_type", "hairstyle"); // Gerekli olan task_type parametresi

                var response = await client.ExecuteAsync(request);
                if (response.IsSuccessful)
                {
                    var jsonResponse = System.Text.Json.JsonDocument.Parse(response.Content);
                    var base64Image = jsonResponse.RootElement.GetProperty("data").GetProperty("image").GetString();

                    if (string.IsNullOrEmpty(base64Image))
                    {
                        return StatusCode(500, "API'den boş bir görsel verisi döndü.");
                    }

                    var imageDataUrl = $"data:image/png;base64,{base64Image}";
                    return View("Result", imageDataUrl);
                }
                else
                {
                    // API yanıtını detaylı logla
                    Console.WriteLine("API Yanıtı: " + response.Content);
                    return StatusCode((int)response.StatusCode, "API isteği başarısız oldu: " + response.Content);
                }

            }
            finally
            {
                // Geçici dosyayı temizle
                if (System.IO.File.Exists(tempFilePath))
                {
                    System.IO.File.Delete(tempFilePath);
                }
            }
        }
    }
}

WEB_PROGRAMLAMA_PROJESI_2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_Denemeler_Frontnend</title>

    <link href="~/css/Anasayfa.css" rel="stylesheet" />  <!--Css -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> <!--Bootstrap css linki-->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--ikon Kullanımı için-->
</head>
<body class="bg-black">
    <header>
        <div class="navbar navbar-expand-sm bg-black">
            <div class="container">
                <!-- Hamburger Menu Button -->
                <button class="navbar-toggler bg-white mt-3" type="button" data-bs-toggle="collapse" data-bs-target="#nContent"
                        aria-expanded="false" aria-label="menüyü açma kapama">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Logo -->
                <div class="navbar-brand">
                    <a asp-controller="Home" asp-action="Anasayfa">
                        <img src="~/İmages/logo.png" alt="logo" class="rounded-circle img-fluid img-thumbnail" style="width: 4rem; height: 4rem;">
                    </a>
                </div>

                <!-- Menu and Login Button -->
                <div class="collapse navbar-collapse" id="nContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item"><a class="nav-link text-white" asp-controller="Home" asp-action="Anasayfa">ANASAYFA</a></li>
                        <li class="nav-item"><a class="nav-link text-white" asp-controller="Home" asp-action="Tarihce">TARİHÇE</a></li>
                        <li class="nav-item"><a class="nav-link text-white" asp-controller="AI" asp-action="Index">YAPAY ZEKA ÖNERİ</a></li>
                        <!-- Login Button for Small Screens -->
                        @if (ViewBag.Kim == 1) // Giriş yapılmadıysa

                        {
                            <li class="nav-item d-sm-none"><a class="nav-link text-white" asp-controller="Home" asp-action="AdminPanel">Admin Panel</a></li>
                        }



                        else if (ViewBag.Kim == 3)
                        {
                            <li class="nav-item d-sm-none"><a class="nav-link text-white" asp-controller="Home" asp-action="RandevuEkleme">Kullanıcı Paneli</a></li>
                        }

                        else

                        {
                            <li class="nav-item d-sm-none"><a class="nav-link text-white" asp-controller="Home" asp-action="AdminPanel">Admin Panel</a></li>
                        }
                         </ul>
                </div>
                @if (ViewBag.Kim == 1) // Giriş yapılmadıysa

                {
                    <div class="d-none d-sm-block ms-auto">
                        <ul class="navbar-nav mx-auto">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="AdminPanel">Admin Panel</a>
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Logout">Çıkış Yap</a>
                        </ul>
                    </div>
                }



                else if (ViewBag.Kim == 3)

                {
                    <div class="d-none d-sm-block ms-auto">
                        <ul class="navbar-nav mx-auto">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="RandevuEkleme">Kullanıcı Paneli</a>
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Logout">Çıkış Yap</a>
                        </ul>
                    </div>
                }

                else

                {
                    <div class="d-none d-sm-block ms-auto">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Login">GİRİŞ YAP</a>
                    </div>
                }
            </div>
        </div>
    </header>




    <div class="container-fluid p-0 m-0 bg-black">
        <main role="main" class="p-0 m-0 bg-black">
            <!-- View içerisindeki dinamik içerik buraya yüklenecek -->
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    <footer class="border-top footer text-muted border-0 mt-2">
        <div class="container-fluid bg-black border-0">
            <!-- İsim ve Logo -->
            <div class="text-center mt-3">
                <i class="fa-solid fa-scissors pt-2" style="font-size: 80px; color:white"></i>
                <span class="text-white" style="font-size: 30px; vertical-align: middle;">BLK-ALK</span>
            </div>

            <!-- İletişim Bilgileri -->
            <div class="text-center pt-3">
                <p class="text-white">Esentepe, Esentepe Kampüsü, Üniversite Cd. 54050 Serdivan / Sakarya | 0544 223 12 12</p>
                <p class="text-white">Designed by Bedirhan BALTIK and İbrahim ALİKILIÇ</p>
            </div>

            <!-- Sosyal Medya Linkleri -->
            <div class="container pt-3 text-center" style="column-gap:10px">
                <div>
                    <a href="https://www.instagram.com/" class="text-white fs-3 me-3">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                    <a href="https://twitter.com/login?lang=tr" class="text-white fs-3 me-3">
                        <i class="fa-brands fa-twitter"></i>
                    </a>
                    <a href="https://www.youtube.com/" class="text-white fs-3 me-3">
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript Dosyaları -->
    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

    <!-- jQuery (Gerekliyse) -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <!-- Site Özel JavaScript -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Ekstra Scriptler için Section -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>